### ISSUE TITLE
CallSessionObject error parsing JSON array to a single CallParty object rather than a list

### ISSUE THREAD

**Issue by ryantannenberg** [ringcentral/ringcentral-java#11]
When running the following:

```
RestClient rc = new RestClient(CLIENT_ID, CLIENT_SECRET, SANDBOX_SERVER);
rc.authorize(USERNAME, EXTENSION, PASSWORD);

MakeCallOutRequest requestBody = new MakeCallOutRequest();
requestBody.from(newMakeCallOutCallerInfoRequestFrom().deviceId(DEVICE_ID));
requestBody.to(newMakeCallOutCallerInfoRequestTo().extensionNumber(phoneNumber));
rc.restapi().account().telephony().callout().post(requestBody);
```

I unfortunately encounter an error from fastJSON in the `parseObject()` call of the `post(requestBody)` call. This is the text of that error:

`com.alibaba.fastjson.JSONException: syntax error, expect {, actual [, pos 188, fieldName parties`

It's important to note here that although the program crashes, the call is still placed. If I look at the response received from the server, position 188 corresponds to an array object containing call parties.

It seems like the problem is that the CallSessionObject to which the `parties` array of the JSON is being parsed needs to have the `parties` field be a List of CallParty objects, not a single CallParty. [This article regarding fastJSON DataBinds](https://github.com/alibaba/fastjson/wiki/Samples-DataBind) seems to confirm that array objects such as the `parties` array returned by RingCentral will parse to List objects (from the Output, Decode, and Group.java sections of that page, in which a sample array is parsed to a List<User>). Per the RingCentral API examples, calls can have multiple parties and multiple parties can be returned in a JSON object if a GET request is made to `telephony/sessions`, meaning that storing more than one CallParty object would be a requirement.

Could this potentially be fixed?

**Comment by tylerlong** [comment]
@ryantannenberg  Try version 1.0.0.

Re-open if this is still an issue.
