### ISSUE TITLE
Need a simple and documented way to set auth token

### ISSUE THREAD

**Issue by byrnereese** [ringcentral/ringcentral-java#12]
The API Reference supports a "Try it out" feature which allows someone to copy-and-paste a code sample that just works. This system works well for cURL requests because the framework is able to insert the HTTP Bearer token directly into the "code sample." However, we cannot do that with any specific language because there is not a clear/obvious way to initialize the client/SDK with an already-existant token.
 
<img width="1155" alt="Screen Shot 2019-08-26 at 5 51 56 PM" src="https://user-images.githubusercontent.com/28429/63732683-3d0db180-c82a-11e9-931b-412e6b6c267d.png">

We need a simple and single API call for getting the Bearer token in this SDK. Something to the effect of:

> sdk.platform().auth().setData(...)

If a capability like this already exists, then can we add that to the documentation?

Acceptance criteria includes the very subjective criteria of the solution not feeling like a "hack." It should not feel like the developer is going into set the value via a backdoor, but by setting it via a public and sanctioned manner.

**Comment by benny-regev-correnet** [comment]
I created a service that has a property RestClient and I initialize it in constructor: 
`
    public class RingCentralService {
        private final RestClient client;

        RingCentralService(@Value("${rc.clientId}") String clientID, @Value("${rc.clientSecret}") String clientSecret, @Value("${rc.url}") String url) {
            this.client = new RestClient(clientID, clientSecret, url);
        }

        public RestClient getClient() {
            return this.client;
        }
    }
`

now, to get token I use:
`TokenInfo tokenInfo = rcService.getClient().authorize("username", "extension", "password");`

Then you can use it creating your HttpRequest:
`
    HttpRequest request = HttpRequest.newBuilder()
                                .uri(URI.create(RC_URL + RESTAPI_VERSION + "/dictionary/country"))
                                .timeout(Duration.ofSeconds(60))
                                .header(HEADER_CONTENT_TYPE, APPLICATION_JSON)
                                .header(HEADER_AUTHORIZATION, String.format("%s %s", tokenInfo.token_type, tokenInfo.access_token))
                                .GET()
                                .build();

`

or by using RestClient from RingCentral API or SDK:
`
    TokenInfo tokenInfo = rcService.getClient().authorize("<username>", "<extension>", "<user-password>");
    var params = new ListExtensionsParameters();
    params.type = new String[]{"User"};
    var extensions = rcService.getClient().restapi().account().extension().list(params);
`

Hope it helps.

**Comment by tylerlong** [comment]
For this SDK , token is a public field and you can set it directly:

https://github.com/ringcentral/ringcentral-java/blob/dfe4c212c5060fb263167b12f89e97dc409be0d2/src/main/java/com/ringcentral/RestClient.java#L22
