### ISSUE TITLE
ExtensionUpdateRequest fails when try to pass transition

### ISSUE THREAD

**Issue by salnikovp0** [ringcentral/ringcentral-java#19]
When I try to call the extension update.
I know that I need to pass 
example: extensionUpdateRequest.transition(new UserTransitionInfo[]{new UserTransitionInfo().sendWelcomeEmail(false)});

but it fails with this message
{
  "errorCode" : "InvalidParameter",
  "message" : "Parameter [transition] value is invalid.",
  "errors" : [ {
    "errorCode" : "CMN-101",
    "message" : "Parameter [transition] value is invalid.",
    "parameterName" : "transition"
  } ],
  "parameterName" : "transition"
}

need to change it to 
extensionUpdateRequest.transition(new UserTransitionInfo().sendWelcomeEmail(false));
and then it would work, accept an UserTransitionInfo

**Comment by tylerlong** [comment]
I think this is a swagger spec issue, because the spec says it should be an array:

https://github.com/ringcentral/RingCentral.Net/blob/master/code-generator/rc-platform.yml

```
transition:
        type: array
        items:
          $ref: '#/definitions/UserTransitionInfo'
          description: For NotActivated extensions only. Welcome email settings
```

I will file an internal ticket for the spec team.

**Comment by tylerlong** [comment]
Fixed
