### ISSUE TITLE
None of the Koitlin migrated code throws RestException object

### ISSUE THREAD

**Issue by gule001** [ringcentral/ringcentral-java#21]
None of the Koitlin migrated code throws RestException objects. 

In essence, the Java interoperability is broken because of this.  

How is one supposed to handle errors when calling the Koitlin API from Java which is the only API provided in your documentation page?

Thankfully, the Koitlin calls still wrap some Java code that can throw proper Exceptions up to client java code that uses the API. 

You need to decorate a bunch of your Koitlin methods with @Throws:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throws/

I would call this issue major.

**Comment by tylerlong** [comment]
Today I wrote a demo project https://github.com/tylerlong/ringcentral-jar-demo/blob/main/src/HelloWorld.java#L15

I couldn't compile until the Intellij IDEA CE added the throw statements for me. I guess for some reason the IDE is still able to figure out what are thrown by the code.

**Comment by tylerlong** [comment]
Fixed
