### ISSUE TITLE
GetInfoExtensionResponse parsing issue

### ISSUE THREAD

**Issue by salnikovp0** [ringcentral/ringcentral-java#27]
tried to create 

use 1.6.0 SDK version

get request on get extensions
and parse the 101 extension with jakson over GetInfoExtensionResponse.class
started the get that issues couple of days ago on UAT environment 

And have the next error stack trace:
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Unrecognized field "empty" (class com.ringcentral.definitions.GetExtensionInfoResponse), not marked as ignorable (24 known properties: "contact", "departments", "regionalSettings", "partnerId", "permissions", "site", "extensionNumber", "setupWizardState", "customFields", "extensionNumbers", "uri", "account", "profileImage", "type", "id", "roles", "statusInfo", "references", "name", "serviceFeatures", "status", "callQueueInfo", "hidden", "upWizardState"])
api              | 2021-06-01T12:42:21.433594156Z  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.ringcentral.definitions.GetExtensionInfoResponse["empty"])] with root cause
api              | 2021-06-01T12:42:21.433601128Z com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "empty" (class com.ringcentral.definitions.GetExtensionInfoResponse), not marked as ignorable (24 known properties: "contact", "departments", "regionalSettings", "partnerId", "permissions", "site", "extensionNumber", "setupWizardState", "customFields", "extensionNumbers", "uri", "account", "profileImage", "type", "id", "roles", "statusInfo", "references", "name", "serviceFeatures", "status", "callQueueInfo", "hidden", "upWizardState"])

**Comment by tylerlong** [comment]
@salnikovp0  I recommend you to try the latest SDK version 1.7.3

And it is appreciated if you could post some code snippets to reproduce the issue. 
And can you reproduce the issue in sandbox or production environment?

**Comment by salnikovp0** [comment]
I have access only to UAT environment.
here is a code example in java

var response = executeRequest("GET", "account/~/extension", "");
var map = mapper.readValue(response.body(), Map.class);
var usersNotActivated = (List<Map<String, String>>) map.get("records");
var user = usersNotActivated.stream()
        .filter(a -> a.getOrDefault("extensionNumber", "").equals("101"))
        .findFirst();

if (user.isPresent()) {
    return mapper.convertValue(user, GetExtensionInfoResponse.class);
} else {
    return null;
}

it fall in the parsing GetExtensionInfoResponse.

again this code worked long time(6 month)

**Comment by tylerlong** [comment]
That's not the way that we are expecting you to use the SDK.
Please check https://github.com/ringcentral/ringcentral-java/blob/master/samples.md#listextensions
You could just replace the whole method with
```java
GetExtensionListResponse result = rc.restapi().account().extension().list();
return result.records.filter(....).findFirst();
```

**Comment by tylerlong** [comment]
The exception is thrown by `return mapper.convertValue(user, GetExtensionInfoResponse.class);`
What is `mapper`?  We don't support it if it is your custom code.

And it should be `GetExtensionListInfoResponse` instead of `GetExtensionInfoResponse`  according to https://github.com/ringcentral/ringcentral-java/blob/master/src/main/java/com/ringcentral/definitions/GetExtensionListResponse.java#L13
