### ISSUE TITLE
Release 0.6 JRE incompatibility

### ISSUE THREAD

**Issue by ddugovic** [ringcentral/ringcentral-java#29]
My team is attempting to add SSO support to our application which uses SDK v0.6.4.  Release 0.6.4 is compatible with JRE 8 (maybe earlier?) whereas Release 0.6.5 requires JRE 12+:

```
java.lang.UnsupportedClassVersionError: com/ringcentral/RestClient has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Thankfully 0.6.5 source code is available so I can compile as needed (although my team might not believe me); could you please recompile the 0.6.5 SDK (or make a release 0.6.6) which is compatible with Java 8?

**Comment by tylerlong** [comment]
The latest version is compatible with Java 8: https://github.com/ringcentral/ringcentral-java/blob/master/build.gradle#L11

We are not going to recompile an old version. It is recommended to upgrade.
