### ISSUE TITLE
How to logout in Android?

### ISSUE THREAD

**Issue by akashk1992** [ringcentral/ringcentral-java#3]
While login I use WEbView. After successful login user authorises app with permissions.
But when I logout/revoke ringcentral using api in my app and then when I try to login it show only "Authorize" page of RingCentral in WebView rather it should display login password view.

So how to logout in my app so that while authorising again it should ask login password.?

**Comment by tylerlong** [comment]
Hi @akashk1992 for WebView I assume you are talking about JavaScript. This project is for Java only.

Could you please post your question to https://github.com/ringcentral/ringcentral-js ?
