### ISSUE TITLE
HttpClient.QueryParameter is final and the constructor is package protected

### ISSUE THREAD

**Issue by afm497** [ringcentral/ringcentral-java#7]
In the get, post, put, etc, etc methods, there is an optional array of HttpClient.QueryParameter arguments. While this would be a preferable way to call these methods, the QueryParameter class is final and the contstructor is package protected. It's unusable, though your tests work just fine because they are in the com.ringcentral package. Is this the preferred library for integration with ring central (in java) or is there another library I'm missing??

**Comment by tylerlong** [comment]
This is the official Java SDK for RingCentral.
Thank you for reporting this issue. It has been fixed in version 0.6.4.
Nobody else ever reported this issue to me, it is pretty weird.

**Comment by tylerlong** [comment]
Feel free to post more issues. Or you can talk to me directly via Glip: https://glipped.herokuapp.com/

**Comment by afm497** [comment]
Thanks for fixing that so quickly! I'll join that glip group today. What is best way to handle issues? Would you prefer posting bugs here or would you like a pull request made with a proposed fix already in there?

**Comment by tylerlong** [comment]
You can either post issues or pull requests, both are welcome!
