### ISSUE TITLE
Send Fax response

### ISSUE THREAD

**Issue by PacoVu** [ringcentral/ringcentral-java#9]
There seems no way to get the response after sending a Fax message. Passing the MessageInfo.class or FaxResponse.class would fail with an error.

`FaxResponse response = restClient.restApi().account().extension().fax().post(requestBody, FaxResponse.class);`

Or

`MessageInfo response = restClient.restApi().account().extension().fax().post(requestBody, MessageInfo.class);`

com.ringcentral.RestException: HTTP status code: 400

{
  "errorCode" : "CMN-101",
  "message" : "Parameter [originalMessageId] value is invalid",
  "errors" : [ {
    "errorCode" : "CMN-101",
    "message" : "Parameter [originalMessageId] value is invalid",
    "parameterName" : "originalMessageId"
  } ],
  "parameterName" : "originalMessageId"
}

**Comment by tylerlong** [comment]
Try latest version
